---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
spec:
  selector: 
    matchLabels: 
      app: pollvoteapp
  template:
    metadata:
      labels:
        app: pollvoteapp
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        volumeMounts: 
        #persistent volume claim
        - mountPath: /data/db
          name: mongo-pvc
      volumes:
      - name: mongo-pvc
        persistentVolumeClaim:
          claimName: mongo-pvc
---